name: Compilar APK do Snake
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Configurar Go
        uses: actions/setup-go@v5 # Atualizado para v5
        with:
          go-version: '1.21'

      - name: Instalar Gomobile e Dependências
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          go mod init snake_projeto || true
          go mod tidy

      - name: Compilar APK
        run: |
          # Tentando compilar o snak.go
          gomobile build -target=android -o snake.apk snak.go

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4 # AQUI ESTAVA O ERRO! Atualizado para v4
        with:
          name: meu-aplicativo-apk
          path: snake.apk
